In [35]:
import random
import numpy as np

In [3]:
age=[]
for i in range(100):
	age.append(random.randint(20,80))

In [17]:
age=pd.Series(age)

In [5]:
salary=[]
for i in range(100):
	salary.append(random.randint(20000,100000))

In [18]:
salary=pd.Series(salary)

In [12]:
designation = []
for i in range(100):
    if(salary[i]>20000 and salary[i]<=40000):
        designation.append("HR")
    elif(salary[i]>=41000 and salary[i]<=60000):
        designation.append("Data Analyst")
    elif(salary[i]>=61000 and salary[i]<=80000):
        designation.append("Data Scientist")
    else:
        designation.append("ML Engineer")

In [19]:
designation=pd.Series(designation)

In [25]:
import pandas as pd
dataset = pd.DataFrame(columns=['age','salary','designation'])

In [27]:
dataset['age']=age

In [29]:
dataset['salary']=salary

In [30]:
dataset['designation']=designation

In [37]:
dataset['index'] = np.arange(0,100)

In [38]:
dataset.pivot_table(index='index',columns='designation',values='salary')

designation  Data Analyst  Data Scientist  HR  ML Engineer
index
0                 41347.0             NaN NaN          NaN
1                     NaN             NaN NaN      90100.0
2                     NaN         74629.0 NaN          NaN
3                     NaN         69466.0 NaN          NaN
4                     NaN             NaN NaN      91396.0
...                   ...             ...  ..          ...
95                    NaN             NaN NaN      96974.0
96                    NaN         65579.0 NaN          NaN
97                    NaN         75110.0 NaN          NaN
98                    NaN             NaN NaN      92637.0
99                43479.0             NaN NaN          NaN

[100 rows x 4 columns]

In [39]:
dataset.reset_index()

    level_0  age  salary     designation  index
0         0   33   41347    Data Analyst      0
1         1   50   90100     ML Engineer      1
2         2   24   74629  Data Scientist      2
3         3   79   69466  Data Scientist      3
4         4   72   91396     ML Engineer      4
..      ...  ...     ...             ...    ...
95       95   73   96974     ML Engineer     95
96       96   78   65579  Data Scientist     96
97       97   78   75110  Data Scientist     97
98       98   43   92637     ML Engineer     98
99       99   43   43479    Data Analyst     99

[100 rows x 5 columns]