In [1]:
import numpy as np
import pandas as pd

##### Re-Indexing & Altering labels

In [2]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35]
}

In [5]:
df = pd.DataFrame(data,index=['a','b','c'])
df

      Name  Age
a    Alice   25
b      Bob   30
c  Charlie   35

In [6]:
df.reindex(['c', 'a', 'b'])

      Name  Age
c  Charlie   35
a    Alice   25
b      Bob   30

In [7]:
df.reindex(['c', 'a', 'b', 'p'])

      Name   Age
c  Charlie  35.0
a    Alice  25.0
b      Bob  30.0
p      NaN   NaN

In [8]:
df.reindex(['p', 'q', 'r'])

  Name  Age
p  NaN  NaN
q  NaN  NaN
r  NaN  NaN

In [9]:
df

      Name  Age
a    Alice   25
b      Bob   30
c  Charlie   35

In [10]:
df.reindex(columns=['Age', 'Name'])

   Age     Name
a   25    Alice
b   30      Bob
c   35  Charlie

In [11]:
df

      Name  Age
a    Alice   25
b      Bob   30
c  Charlie   35

##### Rename index and columns

In [12]:
df.rename(index={'a':'p', 'c':'q'}, columns={'Name':'First Name', 'Age':'Current Age'})

  First Name  Current Age
p      Alice           25
b        Bob           30
q    Charlie           35

In [13]:
df

      Name  Age
a    Alice   25
b      Bob   30
c  Charlie   35

In [14]:
df.index

Index(['a', 'b', 'c'], dtype='str')

In [15]:
# Directly Replace Index or Column Labels

df.index = ['X', 'Y', 'Z']
df.columns = ['PersonName', 'PersonAge']

In [16]:
df

  PersonName  PersonAge
X      Alice         25
Y        Bob         30
Z    Charlie         35

In [17]:
print(df.index)

Index(['X', 'Y', 'Z'], dtype='str')

In [18]:
print(df.columns)

Index(['PersonName', 'PersonAge'], dtype='str')

In [19]:
df.reset_index(inplace=True)

In [20]:
df

  index PersonName  PersonAge
0     X      Alice         25
1     Y        Bob         30
2     Z    Charlie         35

In [21]:
df.drop(columns=['index'], inplace=True)

In [22]:
df

  PersonName  PersonAge
0      Alice         25
1        Bob         30
2    Charlie         35

##### Pivoting

In [23]:
data = {
    "Date": ["2024-01-01", "2024-01-01", "2024-01-02", "2024-01-02"],
    "Product": ["Laptop", "Mouse", "Laptop", "Mouse"],
    "Sales": [1200, 100, 1300, 120],
}

df = pd.DataFrame(data)

In [24]:
df

         Date Product  Sales
0  2024-01-01  Laptop   1200
1  2024-01-01   Mouse    100
2  2024-01-02  Laptop   1300
3  2024-01-02   Mouse    120

In [25]:
df.pivot(index="Date", columns="Product", values="Sales")

Product     Laptop  Mouse
Date
2024-01-01    1200    100
2024-01-02    1300    120

In [26]:
df.pivot(index="Product", columns="Date", values="Sales")
#         1st_Jan   2nd_Jan
# Laptop  1200      1300
# Mouse   100       120

Date     2024-01-01  2024-01-02
Product
Laptop         1200        1300
Mouse           100         120

In [27]:
df.pivot_table(index="Date", columns="Product", values="Sales")

Product     Laptop  Mouse
Date
2024-01-01  1200.0  100.0
2024-01-02  1300.0  120.0

In [ ]:
df.pivot_table(index="Date", columns="Product", values="Sales", aggfunc="sum")

In [28]:
data2 = {
    "Date": ["2024-01-01", "2024-01-01", "2024-01-02", "2024-01-02", "2024-01-01", "2024-01-02"],
    "Product": ["Laptop", "Mouse", "Laptop", "Mouse", "Laptop", "Mouse"],
    "Sales": [1200, 100, 1300, 120, 560, 320],
}

df2 = pd.DataFrame(data2)

In [29]:
df2

         Date Product  Sales
0  2024-01-01  Laptop   1200
1  2024-01-01   Mouse    100
2  2024-01-02  Laptop   1300
3  2024-01-02   Mouse    120
4  2024-01-01  Laptop    560
5  2024-01-02   Mouse    320

In [33]:
df2.pivot_table(index="Date", columns="Product", values="Sales",aggfunc='sum')

Product     Laptop  Mouse
Date
2024-01-01    1760    100
2024-01-02    1300    440

In [ ]:
df2.pivot_table(index="Date", columns="Product", values="Sales", aggfunc="mean")

In [ ]:
df2.pivot_table(index="Date", columns="Product", values="Sales", aggfunc="sum")

In [ ]:
df_trans = pd.read_csv("transactions.csv")

In [ ]:
df_trans

In [ ]:
df_trans.pivot_table(index="category", columns="name", values="amount", aggfunc="mean")

In [ ]:
pivot_tbl = df_trans.pivot_table(index="category", columns="name", values="amount", aggfunc="sum")

In [ ]:
pivot_tbl

In [ ]:
print(pivot_tbl["Alice Brown"].sum())

In [ ]:
for col in pivot_tbl.columns:
    print(f"{col} => {pivot_tbl[col].sum()}")

##### groupby() Function

In [34]:
data = {
    'Department': ['IT', 'IT', 'HR', 'HR', 'Finance', 'Finance'],
    'Employee': ['A', 'B', 'C', 'D', 'E', 'F'],
    'Salary': [60000, 65000, 50000, 52000, 70000, 71000]
}

df_hr = pd.DataFrame(data)

df_hr

  Department Employee  Salary
0         IT        A   60000
1         IT        B   65000
2         HR        C   50000
3         HR        D   52000
4    Finance        E   70000
5    Finance        F   71000

In [35]:
df_hr.groupby(by='Department')

In [36]:
df_hr.groupby(by='Department')['Salary']

In [37]:
df_hr.groupby(by='Department')['Salary'].mean()

Department
Finance    70500.0
HR         51000.0
IT         62500.0
Name: Salary, dtype: float64

In [38]:
df_hr.groupby(by=['Department', 'Employee'])['Salary'].mean()

Department  Employee
Finance     E           70000.0
            F           71000.0
HR          C           50000.0
            D           52000.0
IT          A           60000.0
            B           65000.0
Name: Salary, dtype: float64

In [39]:
df_hr.groupby(by='Department')['Salary'].agg(['sum', 'mean', 'count'])

               sum     mean  count
Department
Finance     141000  70500.0      2
HR          102000  51000.0      2
IT          125000  62500.0      2

In [ ]:
df_hr.groupby(by='Department')['Salary'].agg(Total_Sum='sum', Avg='mean', Count='count')

In [2]:
# Using groupby().apply() with custom function

df = pd.DataFrame({
    'Team': ['A', 'A', 'B', 'B', 'C', 'C'],
    'Player': ['P1', 'P2', 'P3', 'P4', 'P5', 'P6'],
    'Score': [15, 18, 10, 25, 20, 23]
})

In [3]:
df

  Team Player  Score
0    A     P1     15
1    A     P2     18
2    B     P3     10
3    B     P4     25
4    C     P5     20
5    C     P6     23

In [8]:
def score_diff(x):
    return x.max() - x.min()


df_apply = df.groupby('Team')['Score'].apply(score_diff)

df_transform = df.groupby('Team')['Score'].transform(score_diff)

In [9]:
df_apply

Team
A     3
B    15
C     3
Name: Score, dtype: int64

In [10]:
df_transform

0     3
1     3
2    15
3    15
4     3
5     3
Name: Score, dtype: int64

In [43]:
# Filter groups with team total score > 35
total_score = df.groupby('Team')['Score'].sum()

high_score_teams = total_score[total_score > 35].index

filtered_df = df[df['Team'].isin(high_score_teams)]
filtered_df

  Team Player  Score
4    C     P5     20
5    C     P6     23

##### transform() function

In [ ]:
df

In [44]:
df['New_Score'] = df['Score'].transform(lambda x: x + 5)

In [45]:
df

  Team Player  Score  New_Score
0    A     P1     15         20
1    A     P2     18         23
2    B     P3     10         15
3    B     P4     25         30
4    C     P5     20         25
5    C     P6     23         28

In [46]:
def disp(n):
    return n+10

df['Diff_Score'] = df['Score'].transform(disp)

In [47]:
df

  Team Player  Score  New_Score  Diff_Score
0    A     P1     15         20          25
1    A     P2     18         23          28
2    B     P3     10         15          20
3    B     P4     25         30          35
4    C     P5     20         25          30
5    C     P6     23         28          33

In [ ]:
df.drop(columns=['New_Score', 'Diff_Score'], inplace=True)

In [ ]:
df

In [ ]:
df['Avg_Score'] = df.groupby(by='Team')['Score'].transform('mean')

df

In [ ]:
df.groupby(by='Team')['Score'].apply('mean')