In [1]:
import numpy as np
import pandas as pd

##### Handling Categorical Data

In [2]:
df = pd.DataFrame({
    'Color': ['Red', 'Blue', 'Green', 'Red', 'Green']
})

In [3]:
df

   Color
0    Red
1   Blue
2  Green
3    Red
4  Green

In [4]:
df.dtypes

Color    str
dtype: object

In [5]:
df['Color'] = df['Color'].astype('category')

In [6]:
df

   Color
0    Red
1   Blue
2  Green
3    Red
4  Green

In [7]:
df.dtypes

Color    category
dtype: object

In [8]:
sizes = pd.Categorical(['S', 'M', 'L', 'S', 'M', 'M', 'S', 'L'], categories=['S', 'M', 'L'], ordered=True)

sizes

['S', 'M', 'L', 'S', 'M', 'M', 'S', 'L']
Categories (3, str): ['S' < 'M' < 'L']

In [9]:
df_grades = pd.DataFrame({'Grade': ['A', 'B', 'A', 'C', 'B', 'A']})

In [10]:
df_grades

  Grade
0     A
1     B
2     A
3     C
4     B
5     A

In [11]:
df_grades['Grade'] = df_grades['Grade'].astype('category')

In [13]:
df_grades.dtypes

Grade    category
dtype: object

In [14]:
df_grades['Grade'].value_counts()

Grade
A    3
B    2
C    1
Name: count, dtype: int64

In [15]:
df = pd.DataFrame({
    'City': ['Delhi', 'Mumbai', 'Delhi', 'Mumbai', 'Delhi'],
    'Sales': [200, 150, 300, 400, 250]
})

In [16]:
df

     City  Sales
0   Delhi    200
1  Mumbai    150
2   Delhi    300
3  Mumbai    400
4   Delhi    250

In [17]:
df.groupby(by="City").sum()

        Sales
City
Delhi     750
Mumbai    550

In [18]:
df['City'] = df['City'].astype('category')

In [19]:
df

     City  Sales
0   Delhi    200
1  Mumbai    150
2   Delhi    300
3  Mumbai    400
4   Delhi    250

In [20]:
df.groupby(by="City").sum()

        Sales
City
Delhi     750
Mumbai    550

In [21]:
df['expense'] = pd.Series([1000, 1200, 2000, 2400, 3000])

In [22]:
df

     City  Sales  expense
0   Delhi    200     1000
1  Mumbai    150     1200
2   Delhi    300     2000
3  Mumbai    400     2400
4   Delhi    250     3000

In [23]:
df.groupby(by="City").sum()

        Sales  expense
City
Delhi     750     6000
Mumbai    550     3600

In [30]:
df = pd.DataFrame({
    'Size': ['M', 'S', 'L', 'M'],
    'Item': ['Shirt', 'Pants', 'Shirt', 'Cap']
})

In [31]:
df

  Size   Item
0    M  Shirt
1    S  Pants
2    L  Shirt
3    M    Cap

In [35]:
df['Size'] = pd.Categorical(df['Size'], categories=['S', 'M', 'L'], ordered=True)

In [36]:
df

  Size   Item
0    M  Shirt
1    S  Pants
2    L  Shirt
3    M    Cap

In [37]:
df.sort_values(by='Size')

  Size   Item
1    S  Pants
0    M  Shirt
3    M    Cap
2    L  Shirt

In [38]:
df

  Size   Item
0    M  Shirt
1    S  Pants
2    L  Shirt
3    M    Cap

In [40]:
mask = df['Size'] >= 'M'

In [41]:
df[mask]

  Size   Item
0    M  Shirt
2    L  Shirt
3    M    Cap

In [42]:
df['is_large'] = df['Size'] > 'M'

In [43]:
df

  Size   Item  is_large
0    M  Shirt     False
1    S  Pants     False
2    L  Shirt      True
3    M    Cap     False

In [44]:
df[df['Size'] > 'M']

  Size   Item  is_large
2    L  Shirt      True

In [45]:
df[df['Size'] > 'S']

  Size   Item  is_large
0    M  Shirt     False
2    L  Shirt      True
3    M    Cap     False

In [46]:
df[df['Size'] == 'S']

  Size   Item  is_large
1    S  Pants     False

In [47]:
df

  Size   Item  is_large
0    M  Shirt     False
1    S  Pants     False
2    L  Shirt      True
3    M    Cap     False

In [48]:
# df['Size'].cat.rename_categories(['Small', 'Medium', 'Large'])
ndf = df['Size'].cat.rename_categories({'S': 'Small', 'M': 'Medium', 'L': 'Large'})

In [49]:
ndf

0    Medium
1     Small
2     Large
3    Medium
Name: Size, dtype: category
Categories (3, str): ['Small' < 'Medium' < 'Large']

In [50]:
employees = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Hannah', 'Ian', 'Jack', 
             'Karen', 'Liam', 'Mona', 'Nina', 'Oscar'],
             'Gender': ['Female', 'Male', 'Male', 'Male', 'Female', 'Male', 'Female', 'Female', 'Male', 'Male', 'Female', 'Male', 'Female', 'Female', 'Male'],
    'Age': [25, 30, 35, 28, 40, 45, 32, 29, 38, 50, 27, 33, 31, 26, 42],
    'Salary': [50000, 60000, 70000, 55000, 80000, 90000, 65000, 58000, 75000, 100000, 
               52000, 67000, 63000, 54000, 85000],
    'Role': ['Engineer', 'Manager', 'Analyst', 'Engineer', 'Director', 'Manager', 'Analyst', 
             'Engineer', 'Director', 'Manager', 'Analyst', 'Engineer', 'Manager', 'Analyst', 'Director']
})

employees

       Name  Gender  Age  Salary      Role
0     Alice  Female   25   50000  Engineer
1       Bob    Male   30   60000   Manager
2   Charlie    Male   35   70000   Analyst
3     David    Male   28   55000  Engineer
4       Eve  Female   40   80000  Director
5     Frank    Male   45   90000   Manager
6     Grace  Female   32   65000   Analyst
7    Hannah  Female   29   58000  Engineer
8       Ian    Male   38   75000  Director
9      Jack    Male   50  100000   Manager
10    Karen  Female   27   52000   Analyst
11     Liam    Male   33   67000  Engineer
12     Mona  Female   31   63000   Manager
13     Nina  Female   26   54000   Analyst
14    Oscar    Male   42   85000  Director

In [51]:
pd.get_dummies(employees, columns=['Gender'])

       Name  Age  Salary      Role  Gender_Female  Gender_Male
0     Alice   25   50000  Engineer           True        False
1       Bob   30   60000   Manager          False         True
2   Charlie   35   70000   Analyst          False         True
3     David   28   55000  Engineer          False         True
4       Eve   40   80000  Director           True        False
5     Frank   45   90000   Manager          False         True
6     Grace   32   65000   Analyst           True        False
7    Hannah   29   58000  Engineer           True        False
8       Ian   38   75000  Director          False         True
9      Jack   50  100000   Manager          False         True
10    Karen   27   52000   Analyst           True        False
11     Liam   33   67000  Engineer          False         True
12     Mona   31   63000   Manager           True        False
13     Nina   26   54000   Analyst           True        False
14    Oscar   42   85000  Director          False         True