In [1]:
import pandas as pd

In [2]:

# Sample Data
customers = pd.DataFrame({
    'customer_id': [1, 2, 3],
    'name': ['Harsh', 'Harsh1', 'Harsh2']
})

orders = pd.DataFrame({
    'order_id': [101, 102, 103],
    'customer_id': [1, 1, 2],
    'order_date': ['2023-01-01', '2023-01-02', '2023-01-03']
})

order_items = pd.DataFrame({
    'order_id': [101, 101, 102],
    'product_id': [501, 502, 501],
    'quantity': [2, 1, 3]
})

products = pd.DataFrame({
    'product_id': [501, 502,503],
    'product_name': ['Laptop', 'Mouse','Keyboard']
})

In [3]:
customers

   customer_id    name
0            1   Harsh
1            2  Harsh1
2            3  Harsh2

In [4]:
orders

   order_id  customer_id  order_date
0       101            1  2023-01-01
1       102            1  2023-01-02
2       103            2  2023-01-03

In [5]:
order_items

   order_id  product_id  quantity
0       101         501         2
1       101         502         1
2       102         501         3

In [6]:
products

   product_id product_name
0         501       Laptop
1         502        Mouse
2         503     Keyboard

In [7]:

# Merge to create a comprehensive analysis DataFrame

In [8]:
df = order_items.merge(products,on='product_id',how = 'right')

In [9]:
df

   order_id  product_id  quantity product_name
0     101.0         501       2.0       Laptop
1     102.0         501       3.0       Laptop
2     101.0         502       1.0        Mouse
3       NaN         503       NaN     Keyboard

In [15]:
products

   product_id product_name
0         501       Laptop
1         502        Mouse
2         503     Keyboard

In [21]:
df1 = order_items.join(products.set_index('product_id'), on='product_id', how='right')

In [22]:
df1

     order_id  product_id  quantity product_name
0.0     101.0         501       2.0       Laptop
2.0     102.0         501       3.0       Laptop
1.0     101.0         502       1.0        Mouse
NaN       NaN         503       NaN     Keyboard